module Tarefa3_2022li1g044_Spec where

import LI12223
import Tarefa3_2022li1g044
import Test.HUnit

testsT3 :: Test
testsT3 = TestLabel "Testes Tarefa 3" $ test ["Teste 1" ~: Jogo (Jogador (2,1)) (Mapa 7 [(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2,[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco])]) ~=? animaJogo (Jogo (Jogador (2,0)) (Mapa 7 [(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum])])) (Move Baixo),
                                              "Teste 2" ~: Jogo (Jogador (1,1)) (Mapa 7 [(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2,[Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco])]) ~=? animaJogo (Jogo (Jogador (1,1)) (Mapa 7 [(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Nenhum]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum])])) (Move Cima),
                                              "Teste 3" ~: Jogo (Jogador (0,3)) (Mapa 7 [(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2,[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (2,3)) (Mapa 7 [(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) Parado,
                                              "Teste 4" ~: Jogo (Jogador (0,0)) (Mapa 7 [(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2,[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (2, 0)) (Mapa 7 [(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 2, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) Parado,
                                              "Teste 5" ~: Jogo (Jogador (2,1)) (Mapa 7 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (2, 1)) (Mapa 7 [(Relva, [Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) (Move Cima), 
                                              "Teste 6" ~: Jogo (Jogador (1,0)) (Mapa 7 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (1, 0)) (Mapa 7 [(Relva, [Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) (Move Baixo), 
                                              "Teste 7" ~: Jogo (Jogador (1,0)) (Mapa 7 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (1, 0)) (Mapa 7 [(Relva, [Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) (Move Direita),
                                              "Teste 8" ~: Jogo (Jogador (3,0)) (Mapa 7 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (3, 0)) (Mapa 7 [(Relva, [Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) (Move Esquerda),
                                              "Teste 9" ~: Jogo (Jogador (0,0)) (Mapa 7 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (0, 0)) (Mapa 7 [(Relva, [Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) (Move Esquerda),
                                              "Teste 10" ~: Jogo (Jogador (6,1)) (Mapa 7 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (6, 1)) (Mapa 7 [(Relva, [Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) (Move Direita),
                                              "Teste 11" ~: Jogo (Jogador (0,2)) (Mapa 7 [(Relva,[Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (0, 2)) (Mapa 7 [(Relva, [Nenhum,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum]),(Estrada 1, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Nenhum]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum]),(Relva , [Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum])])) (Move Esquerda),
                                              "Teste 12" ~: Jogo (Jogador (1,2)) (Mapa 8 [(Relva,[Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Arvore,Arvore,Nenhum]),(Rio (-2),[Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco]),(Estrada 2,[Carro,Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum])]) ~=? animaJogo (Jogo (Jogador (2,2)) (Mapa 8 [(Relva , [Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Arvore,Arvore,Nenhum]),(Rio (-2), [Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum]),(Estrada 2, [Nenhum,Nenhum,Nenhum,Carro,Carro,Nenhum,Carro,Nenhum])])) (Move Esquerda),
                                              "Teste 13" ~: Jogo (Jogador (4,1)) (Mapa 6 [(Relva,[Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Arvore]),(Rio 2,[Nenhum,Tronco,Nenhum,Tronco,Tronco,Tronco]),(Relva,[Nenhum,Nenhum,Nenhum,Arvore,Arvore,Nenhum])]) ~=? animaJogo (Jogo (Jogador (1,1)) (Mapa 6 [(Relva , [Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Arvore]),(Rio 2, [Nenhum,Tronco,Tronco,Tronco,Nenhum,Tronco]),(Relva, [Nenhum,Nenhum,Nenhum,Arvore,Arvore,Nenhum])])) (Move Direita)
                                            ]
                            

